// Generated by scripts/generate-route-seo.mjs — do not edit by hand
export type RouteSeo = { title: string; description: string }

export const ROUTE_SEO: Record<string, RouteSeo> = {
  "/3d-house-tours-las-vegas": {
    "title": "3D House Tours Las Vegas: Virtual Tour Services for Real Estate | Dr. Jan Duffy",
    "description": "Professional 3D house tours and virtual tour services for Las Vegas real estate. Enhance your property listing with immersive virtual tours that attract buyers"
  },
  "/about": {
    "title": "About Dr. Janet Duffy: Las Vegas Real Estate Expert Helping Homes Sell When They Didn't Before",
    "description": "Transforming frustrated homeowners into successful sellers. Specializing in helping Las Vegas homes that didn't sell get sold."
  },
  "/berkshire-hathaway/communication": {
    "title": "Proactive Communication: Why 68% of Expired Listings Had Radio Silence | Dr. Jan Duffy",
    "description": "Your home didn't sell because your agent disappeared. Dr. Jan delivers weekly updates, 24/7 accessibility, and strategic pivots that keep your listing moving to"
  },
  "/berkshire-hathaway/comparison": {
    "title": "Brokerage Comparison: Why | Dr. Jan Duffy",
    "description": "Side-by-side comparison of what each major Las Vegas brokerage delivers - and why"
  },
  "/berkshire-hathaway/marketing-power": {
    "title": "Institutional Marketing Power: Why 87% of Expired Listings Failed | Dr. Jan Duffy",
    "description": "Your home didn't sell because it never reached qualified buyers. Dr. Jan +"
  },
  "/berkshire-hathaway/pricing-mastery": {
    "title": "Pricing Mastery: Why 73% of Expired Listings Were Overpriced | Dr. Jan Duffy",
    "description": "Your home didn't sell because it was priced 5-15% too high. Dr. Jan's PhD-level pricing approach backed by 30 years of Vegas market data ensures accurate pricin"
  },
  "/berkshire-hathaway/turnaround-plan": {
    "title": "The Expired Listing Turnaround Plan: From Failed to Sold — A Structured Relisting Plan | Dr. Jan Duffy",
    "description": "When you switch to Dr. Jan after an expired listing, here's exactly what changes immediately - a systematic 4-week plan that addresses every failure from your p"
  },
  "/best-neighborhoods-las-vegas": {
    "title": "Best Neighborhoods in Las Vegas: Comprehensive Guide to Top Communities | Dr. Jan Duffy",
    "description": "Discover the best neighborhoods in Las Vegas for luxury homes, family living, and value. Expert insights on Summerlin, Henderson, North Las Vegas, and Las Vegas"
  },
  "/boulder-city": {
    "title": "Boulder City, NV Real Estate Expert | Dr. Jan Duffy",
    "description": "Specialized help for Boulder City homes that didn't sell. Expert guidance for successful home sales near Lake Mead and Hoover Dam."
  },
  "/contact": {
    "title": "Contact Dr. Janet Duffy: Let's Talk About Selling Your Home",
    "description": "Your home didn't sell? Let's change that. Reach out today for a free consultation."
  },
  "/didnt-sell": {
    "title": "Why Didn't Your Home Sell? The Most Common Reasons | Dr. Jan Duffy",
    "description": "Understanding why your home didn't sell is the first step to selling it successfully. Here are the most common reasons and how to fix them."
  },
  "/downtown-las-vegas": {
    "title": "Downtown Las Vegas Real Estate Expert | Dr. Jan Duffy",
    "description": "Specialized help for homes that didn't sell in Downtown Las Vegas. Expert guidance for successful home sales in the heart of Sin City."
  },
  "/enterprise": {
    "title": "Enterprise, NV Real Estate Expert | Dr. Jan Duffy",
    "description": "Specialized help for Enterprise homes that didn't sell. Expert guidance for successful home sales in this growing Las Vegas community."
  },
  "/expired-listing-help": {
    "title": "Free Help for Expired Listings | Dr. Jan Duffy",
    "description": "Your listing expired. What happens next? Get expert guidance and a proven plan to sell your home successfully."
  },
  "/home-valuation": {
    "title": "Free Home Value Analysis | Dr. Jan Duffy",
    "description": "Get accurate home value analysis for Las Vegas properties. Expert valuation insights to help you price competitively and sell successfully."
  },
  "/houses-for-sale-las-vegas": {
    "title": "Houses for Sale Las Vegas: Expert Guidance for Buyers and Sellers | Dr. Jan Duffy",
    "description": "Expert guidance for houses for sale in Las Vegas. Specialized help for homes that didn't sell and comprehensive resources for Las Vegas real estate buyers and s"
  },
  "/how-it-works": {
    "title": "How Dr. Jan Helps Homes That Didn't Sell Get Sold",
    "description": "A step-by-step look at Dr. Janet Duffy's proven process for turning expired listings into sold properties. From initial consultation to successful closing."
  },
  "/las-vegas-condos-for-sale": {
    "title": "Las Vegas Condos for Sale: Expert Guide to Condominium Living | Dr. Jan Duffy",
    "description": "Expert guidance on Las Vegas condos for sale in Downtown, high-rise buildings, and luxury communities. Specialized help for condos that didn't sell."
  },
  "/las-vegas-homes": {
    "title": "Las Vegas Homes: Comprehensive Real Estate Guide | Dr. Jan Duffy",
    "description": "Expert guidance on Las Vegas homes for sale across all neighborhoods. Specialized help for Las Vegas homes that didn't sell and comprehensive market insights."
  },
  "/las-vegas-luxury-homes": {
    "title": "Las Vegas Luxury Homes for Sale: Expert Guidance for High-End Properties | Dr. Jan Duffy",
    "description": "Specialized expertise in Las Vegas luxury homes for sale. Expert guidance for buying and selling luxury properties in Summerlin, Henderson, and Las Vegas's most"
  },
  "/las-vegas-mansions": {
    "title": "Las Vegas Mansions: Expert Guide to Luxury Estate Properties | Dr. Jan Duffy",
    "description": "Expert guidance on Las Vegas mansions and luxury estate properties. Specialized expertise in high-end luxury homes in Summerlin, Henderson, and Las Vegas's most"
  },
  "/las-vegas-mls": {
    "title": "Las Vegas MLS: Understanding Multiple Listing Service and Real Estate Listings | Dr. Jan Duffy",
    "description": "Expert guidance on Las Vegas MLS listings and how the Multiple Listing Service works. Learn how professional real estate agents use MLS to market your Las Vegas"
  },
  "/las-vegas-property-tax": {
    "title": "Las Vegas Property Tax: Complete Guide for Homeowners and Buyers | Dr. Jan Duffy",
    "description": "Comprehensive guide to Las Vegas property tax rates, assessments, and exemptions. Essential information for Las Vegas homeowners and homebuyers understanding pr"
  },
  "/las-vegas-real-estate-website": {
    "title": "Las Vegas Real Estate Website | Dr. Jan Duffy",
    "description": "Your comprehensive resource for Las Vegas real estate expertise, market insights, and proven strategies for homes that didn't sell."
  },
  "/neighborhoods/downtown-las-vegas/fremont": {
    "title": "Fremont Street Downtown Las Vegas: Urban Lofts Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for Fremont Street area homes that didn't sell. Expert guidance for successful home sales in Downtown Las Vegas's entertainment district."
  },
  "/neighborhoods/henderson/green-valley": {
    "title": "Green Valley Henderson: Homes That Didn't Sell Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for Green Valley homes that didn't sell. Expert guidance for successful home sales in Henderson's premier master-planned community."
  },
  "/neighborhoods/henderson/lake-las-vegas": {
    "title": "Lake Las Vegas Henderson: Luxury Waterfront Homes Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for Lake Las Vegas homes that didn't sell. Expert guidance for successful home sales in Henderson's premier waterfront community."
  },
  "/neighborhoods/henderson/macdonald-ranch": {
    "title": "MacDonald Ranch Henderson: Golf Course Homes Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for MacDonald Ranch homes that didn't sell. Expert guidance for successful home sales in Henderson's premier golf course community."
  },
  "/neighborhoods/henderson": {
    "title": "Henderson Las Vegas: Affordability, Amenities, and Great Value | Dr. Jan Duffy",
    "description": "Henderson offers Las Vegas residents exceptional value with quality schools, family-friendly communities, and more affordable housing than many other Vegas area"
  },
  "/neighborhoods/north-las-vegas": {
    "title": "North Las Vegas: Affordable New Construction and Growing Communities | Dr. Jan Duffy",
    "description": "North Las Vegas offers exceptional value with new construction, affordable housing, and rapidly developing master-planned communities ideal for families and fir"
  },
  "/neighborhoods/north-las-vegas/skye-canyon": {
    "title": "Skye Canyon North Las Vegas: New Construction Homes Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for Skye Canyon homes that didn't sell. Expert guidance for successful home sales in North Las Vegas's premier new construction community."
  },
  "/neighborhoods": {
    "title": "Las Vegas Neighborhoods Guide: Find Your Perfect Community | Dr. Jan Duffy",
    "description": "Discover the best neighborhoods in Las Vegas. From master-planned communities to urban living, find the perfect area that matches your lifestyle and budget."
  },
  "/neighborhoods/summerlin": {
    "title": "Summerlin Las Vegas: Master-Planned Living at Its Finest | Dr. Jan Duffy",
    "description": "Discover why Summerlin is considered one of the best neighborhoods in Las Vegas. From world-class golf courses to top-rated schools and master-planned communiti"
  },
  "/neighborhoods/summerlin/sun-city": {
    "title": "Sun City Summerlin: Active Adult Homes Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for Sun City Summerlin homes that didn't sell. Expert guidance for successful home sales in Summerlin's premier active adult community."
  },
  "/neighborhoods/summerlin/the-foothills": {
    "title": "The Foothills Summerlin: Mountain View Homes Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for The Foothills homes that didn't sell. Expert guidance for successful home sales in Summerlin's elevated mountain view community."
  },
  "/neighborhoods/summerlin/the-trails": {
    "title": "The Trails Summerlin: Homes That Didn't Sell Expert Help | Dr. Jan Duffy",
    "description": "Specialized help for The Trails homes that didn't sell. Expert guidance for successful home sales in Summerlin's premier trail-accessible community."
  },
  "/": {
    "title": "Selling a Las Vegas Rental with Tenants | Dr. Jan Duffy",
    "description": "Landlord-focused listing strategy — leases, NRS 118A notice, and showings while tenants remain in place"
  },
  "/paradise": {
    "title": "Paradise, NV Real Estate Expert | Dr. Jan Duffy",
    "description": "Helping Paradise homes that didn't sell achieve successful relisting. Expert guidance for Las Vegas neighborhoods near the Strip."
  },
  "/real-estate-agent-scripts-las-vegas": {
    "title": "Real Estate Agent Scripts for Las Vegas: Effective Cold Calling for Expired Listings | Dr. Jan Duffy",
    "description": "Expert real estate scripts tailored for Las Vegas market, specifically for reaching out about expired listings and homes that didn't sell. Proven templates for"
  },
  "/real-estate-las-vegas": {
    "title": "Real Estate Las Vegas: Comprehensive Market Guide | Dr. Jan Duffy",
    "description": "Comprehensive guide to Las Vegas real estate market: neighborhoods, buying and selling, market trends, and expert insights. Specialized help for Las Vegas real"
  },
  "/real-estate-marketing-tools-las-vegas": {
    "title": "Best Real Estate Marketing Tools for Las Vegas Agents | Dr. Jan Duffy",
    "description": "Technology and tools used by successful Las Vegas agents to market properties effectively. From professional photography to lead generation platforms, discover"
  },
  "/realtor-las-vegas": {
    "title": "Realtor Las Vegas: Expert Real Estate Agent for Homes That Didn't Sell | Dr. Jan Duffy",
    "description": "Las Vegas realtor specializing in expired listings and homes that didn't sell. Licensed real estate professional with"
  },
  "/seller-consultation": {
    "title": "Free Seller Consultation - Expert Help for Homes That Didn't Sell | Dr. Jan Duffy",
    "description": "Schedule your free consultation with Dr. Janet Duffy to analyze why your home didn't sell and create a proven strategy for successful relisting."
  },
  "/spring-valley": {
    "title": "Spring Valley, NV Real Estate Expert | Dr. Jan Duffy",
    "description": "Specialized help for Spring Valley homes that didn't sell. Expert guidance for successful home sales in this established Las Vegas community."
  },
  "/success-stories": {
    "title": "Success Stories: Homes That Didn't Sell, Then Sold Successfully | Dr. Jan Duffy",
    "description": "Real results from homeowners whose properties didn't sell initially. Learn how Dr. Janet Duffy helped them sell successfully."
  },
  "/whitney": {
    "title": "Whitney, NV Real Estate Expert | Dr. Jan Duffy",
    "description": "Specialized help for Whitney homes that didn't sell. Expert guidance for successful home sales in this diverse East Las Vegas community."
  },
  "/why-berkshire-hathaway": {
    "title": "Why | Dr. Jan Duffy",
    "description": "Three critical advantages that turn expired listings into sold properties. Institutional marketing power, pricing mastery, and proactive communication that bout"
  },
  "/winchester": {
    "title": "Winchester, NV Real Estate Expert | Dr. Jan Duffy",
    "description": "Specialized help for Winchester homes that didn't sell. Expert guidance for successful home sales in this diverse Las Vegas community."
  },
  "/zipcodes/89052": {
    "title": "Zip Code 89052: Homes That Didn't Sell Expert Help in Boulder City Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89052 homes that didn't sell. Expert guidance for successful home sales in Boulder City and Lake Mead area."
  },
  "/zipcodes/89074": {
    "title": "Zip Code 89074: Homes That Didn't Sell Expert Help in Green Valley Henderson | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89074 homes that didn't sell. Expert guidance for successful home sales in Green Valley and surrounding Henderson areas."
  },
  "/zipcodes/89102": {
    "title": "Zip Code 89102: Homes That Didn't Sell Expert Help in Downtown Las Vegas Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89102 homes that didn't sell. Expert guidance for successful home sales in Downtown Las Vegas and Fremont Street areas."
  },
  "/zipcodes/89103": {
    "title": "Zip Code 89103: Homes That Didn't Sell Expert Help in Summerlin West Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89103 homes that didn't sell. Expert guidance for successful home sales in Summerlin West and surrounding Las Vegas areas."
  },
  "/zipcodes/89113": {
    "title": "Zip Code 89113: Homes That Didn't Sell Expert Help in Spring Valley Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89113 homes that didn't sell. Expert guidance for successful home sales in Spring Valley and surrounding Las Vegas areas."
  },
  "/zipcodes/89117": {
    "title": "Zip Code 89117: Homes That Didn't Sell Expert Help in Summerlin Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89117 homes that didn't sell. Expert guidance for successful home sales in Summerlin and surrounding Las Vegas areas."
  },
  "/zipcodes/89128": {
    "title": "Zip Code 89128: Homes That Didn't Sell Expert Help in Summerlin South Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89128 homes that didn't sell. Expert guidance for successful home sales in Summerlin South and surrounding Las Vegas areas."
  },
  "/zipcodes/89129": {
    "title": "Zip Code 89129: Homes That Didn't Sell Expert Help in Centennial Hills Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89129 homes that didn't sell. Expert guidance for successful home sales in Centennial Hills and Northwest Las Vegas areas."
  },
  "/zipcodes/89131": {
    "title": "Zip Code 89131: Homes That Didn't Sell Expert Help in North Las Vegas Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89131 homes that didn't sell. Expert guidance for successful home sales in North Las Vegas and Skye Canyon areas."
  },
  "/zipcodes/89134": {
    "title": "Zip Code 89134: Homes That Didn't Sell Expert Help in Southwest Las Vegas Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89134 homes that didn't sell. Expert guidance for successful home sales in Southwest Las Vegas and surrounding areas."
  },
  "/zipcodes/89139": {
    "title": "Zip Code 89139: Homes That Didn't Sell Expert Help in Enterprise South Area | Dr. Jan Duffy",
    "description": "Specialized help for zip code 89139 homes that didn't sell. Expert guidance for successful home sales in Enterprise South and Southwest Las Vegas areas."
  }
} as const
